### ISSUE TITLE
How were the diagrams made?

### ISSUE THREAD

**Issue by runtimevic** [Beckhoff-USA-Community/SPT-Libraries#1]
Hello,
How have the UML graphic diagrams been made to put them in the pdf documents?

**Comment by MarkLewis-Beckhoff** [comment]
https://mermaid.live/

**Comment by runtimevic** [comment]
> https://mermaid.live/

and how do you pass the classDiagram made in TwinCAT to mermaid?, 
or do you make it from scratch from mermaid?

**Comment by nshiggins** [comment]
It is a separate tool not Beckhoff related.  The diagrams were made
manually.

**Comment by nshiggins** [comment]
Not as far as I know.  Mermaid is its own markup language that just happens to have the ability to do generic class diagrams.  I chose to use it for a number of reasons, but mostly because I wanted to illustrate the relationships and not necessarily expose all of the locals, etc. in each function block.

**Comment by runtimevic** [comment]
> Not as far as I know. Mermaid is its own markup language that just happens to have the ability to do generic class diagrams. I chose to use it for a number of reasons, but mostly because I wanted to illustrate the relationships and not necessarily expose all of the locals, etc. in each function block.

thanks,
