### ISSUE TITLE
Abort from Clearing not possible

### ISSUE THREAD

**Issue by MrKirkegaard** [Beckhoff-USA-Community/SPT-Libraries#30]
The Parent response abort is not possible in state clearing. 
![image](https://github.com/Beckhoff-USA-Community/SPT-Libraries/assets/9883540/8766b4b0-3e08-4da3-a831-213a57374718)
Both the SubModuleMonitor and ComponentMonitor do not allow the abort command defined in the PackML model.
![image](https://github.com/Beckhoff-USA-Community/SPT-Libraries/assets/9883540/4d3eb900-110f-4aab-b655-e71789be10d9)

**Comment by KeithBaker123** [comment]
Thank you Mr Kirkegaard for your input to our repository.  We take in all issues and discuss them as a team.

On the issue that the SubmoduleMonitor and ComponentMonitor do not take the parentResponse in clearing and directly go to Aborting is done because we use Clearing to reset safety and other alarms. If we responded to them before being cleared, we would end up in a race condition.   So, we would usually have a timeout in Clearing and if the devices did not reset, we would send state engine to Aborting.

We feel that the framework follows PackML and our implementation of the Framework gives you the flexibility to do what you need.

**Comment by MrKirkegaard** [comment]
Hi Keith

Thank you for the feedback. 

Is there a possibility that you can clarify this in the SPT Framework documentation, that ParrentResponseDefinition deliberately has no effect in state clearing?

Is it possible to add a Transition State Timeout function in FB_PackML_BaseModule?

I have had to Extended the FB_PackML_BaseModule to implement a Transition state timeout in all my Equipment Modules and the Unit.
